// AUTO-GENERATED by scripts/refresh-data.mjs — do not edit by hand.
// Latest sourced macro figures (World Bank) + the calibration anchors the model's live overlay
// rides off. `anchors` freeze at seed (the figure paired with the authored composite score);
// `latest` refreshes every cycle and carries forward the last-good value on any rejected fetch.
// The overlay (src/data/empirical.ts) is a no-op while latest === anchors.

export interface LiveFigure { v: number; year: number }
export interface FigureRecord { eco?: LiveFigure; mil?: LiveFigure }
export interface FiguresFile {
  generatedAt: string
  source: string
  anchors: Record<string, FigureRecord>
  latest: Record<string, FigureRecord>
}

export const FIGURES: FiguresFile = /* @generated-json-start */ {
  "generatedAt": "2026-06-17T22:50:49.726Z",
  "source": "World Bank: NY.GDP.MKTP.PP.CD (GDP PPP, current intl $) · MS.MIL.XPND.CD (military expenditure, current US$)",
  "anchors": {
    "usa": {
      "eco": {
        "v": 29184890000000.1,
        "year": 2024
      },
      "mil": {
        "v": 997309000000,
        "year": 2024
      }
    },
    "china": {
      "eco": {
        "v": 38190084585497.8,
        "year": 2024
      },
      "mil": {
        "v": 313658330217.176,
        "year": 2024
      }
    },
    "russia": {
      "eco": {
        "v": 6921249292202.15,
        "year": 2024
      },
      "mil": {
        "v": 148967275140.483,
        "year": 2024
      }
    },
    "india": {
      "eco": {
        "v": 16192422603162.4,
        "year": 2024
      },
      "mil": {
        "v": 86125976248.5524,
        "year": 2024
      }
    },
    "saudi": {
      "eco": {
        "v": 2519570644557.09,
        "year": 2024
      },
      "mil": {
        "v": 80330666666.6667,
        "year": 2024
      }
    },
    "israel": {
      "eco": {
        "v": 570892527370.231,
        "year": 2024
      },
      "mil": {
        "v": 46505298369.3376,
        "year": 2024
      }
    },
    "turkey": {
      "eco": {
        "v": 3902987817630.99,
        "year": 2024
      },
      "mil": {
        "v": 24978735534.6038,
        "year": 2024
      }
    },
    "iran": {
      "eco": {
        "v": 1819806794107.97,
        "year": 2024
      },
      "mil": {
        "v": 7891903306.81818,
        "year": 2024
      }
    },
    "pakistan": {
      "eco": {
        "v": 1570963817829.03,
        "year": 2024
      },
      "mil": {
        "v": 10165952756.2448,
        "year": 2024
      }
    },
    "egypt": {
      "eco": {
        "v": 2225198389821.18,
        "year": 2024
      },
      "mil": {
        "v": 2396211163.82267,
        "year": 2024
      }
    },
    "uae": {
      "eco": {
        "v": 870438615966.339,
        "year": 2024
      },
      "mil": {
        "v": 22755071477.1954,
        "year": 2014
      }
    },
    "iraq": {
      "eco": {
        "v": 665966378219.474,
        "year": 2024
      },
      "mil": {
        "v": 6178546529.67549,
        "year": 2024
      }
    },
    "qatar": {
      "eco": {
        "v": 360218045926.174,
        "year": 2024
      },
      "mil": {
        "v": 15412087912.0879,
        "year": 2022
      }
    },
    "kuwait": {
      "eco": {
        "v": 256830086794.8,
        "year": 2024
      },
      "mil": {
        "v": 7792925565.71038,
        "year": 2024
      }
    },
    "oman": {
      "eco": {
        "v": 220452272078.928,
        "year": 2024
      },
      "mil": {
        "v": 5988296488.94668,
        "year": 2024
      }
    },
    "jordan": {
      "eco": {
        "v": 125019343386.99,
        "year": 2024
      },
      "mil": {
        "v": 2560281690.14085,
        "year": 2024
      }
    },
    "lebanon": {
      "eco": {
        "v": 72600709791.5249,
        "year": 2023
      },
      "mil": {
        "v": 635471571.906355,
        "year": 2024
      }
    },
    "bahrain": {
      "eco": {
        "v": 106347544575.271,
        "year": 2024
      },
      "mil": {
        "v": 1383973404.25532,
        "year": 2024
      }
    },
    "yemen": {
      "eco": {
        "v": 92755605480.1343,
        "year": 2013
      },
      "mil": {
        "v": 1714830843.68747,
        "year": 2014
      }
    },
    "syria": {
      "eco": {
        "v": 107199859817.267,
        "year": 2022
      },
      "mil": {
        "v": 2494887483.1484,
        "year": 2011
      }
    }
  },
  "latest": {
    "usa": {
      "eco": {
        "v": 29184890000000.1,
        "year": 2024
      },
      "mil": {
        "v": 997309000000,
        "year": 2024
      }
    },
    "china": {
      "eco": {
        "v": 38190084585497.8,
        "year": 2024
      },
      "mil": {
        "v": 313658330217.176,
        "year": 2024
      }
    },
    "russia": {
      "eco": {
        "v": 6921249292202.15,
        "year": 2024
      },
      "mil": {
        "v": 148967275140.483,
        "year": 2024
      }
    },
    "india": {
      "eco": {
        "v": 16192422603162.4,
        "year": 2024
      },
      "mil": {
        "v": 86125976248.5524,
        "year": 2024
      }
    },
    "saudi": {
      "eco": {
        "v": 2519570644557.09,
        "year": 2024
      },
      "mil": {
        "v": 80330666666.6667,
        "year": 2024
      }
    },
    "israel": {
      "eco": {
        "v": 570892527370.231,
        "year": 2024
      },
      "mil": {
        "v": 46505298369.3376,
        "year": 2024
      }
    },
    "turkey": {
      "eco": {
        "v": 3902987817630.99,
        "year": 2024
      },
      "mil": {
        "v": 24978735534.6038,
        "year": 2024
      }
    },
    "iran": {
      "eco": {
        "v": 1819806794107.97,
        "year": 2024
      },
      "mil": {
        "v": 7891903306.81818,
        "year": 2024
      }
    },
    "pakistan": {
      "eco": {
        "v": 1570963817829.03,
        "year": 2024
      },
      "mil": {
        "v": 10165952756.2448,
        "year": 2024
      }
    },
    "egypt": {
      "eco": {
        "v": 2225198389821.18,
        "year": 2024
      },
      "mil": {
        "v": 2396211163.82267,
        "year": 2024
      }
    },
    "uae": {
      "eco": {
        "v": 870438615966.339,
        "year": 2024
      },
      "mil": {
        "v": 22755071477.1954,
        "year": 2014
      }
    },
    "iraq": {
      "eco": {
        "v": 665966378219.474,
        "year": 2024
      },
      "mil": {
        "v": 6178546529.67549,
        "year": 2024
      }
    },
    "qatar": {
      "eco": {
        "v": 360218045926.174,
        "year": 2024
      },
      "mil": {
        "v": 15412087912.0879,
        "year": 2022
      }
    },
    "kuwait": {
      "eco": {
        "v": 256830086794.8,
        "year": 2024
      },
      "mil": {
        "v": 7792925565.71038,
        "year": 2024
      }
    },
    "oman": {
      "eco": {
        "v": 220452272078.928,
        "year": 2024
      },
      "mil": {
        "v": 5988296488.94668,
        "year": 2024
      }
    },
    "jordan": {
      "eco": {
        "v": 125019343386.99,
        "year": 2024
      },
      "mil": {
        "v": 2560281690.14085,
        "year": 2024
      }
    },
    "lebanon": {
      "eco": {
        "v": 72600709791.5249,
        "year": 2023
      },
      "mil": {
        "v": 635471571.906355,
        "year": 2024
      }
    },
    "bahrain": {
      "eco": {
        "v": 106347544575.271,
        "year": 2024
      },
      "mil": {
        "v": 1383973404.25532,
        "year": 2024
      }
    },
    "yemen": {
      "eco": {
        "v": 92755605480.1343,
        "year": 2013
      },
      "mil": {
        "v": 1714830843.68747,
        "year": 2014
      }
    },
    "syria": {
      "eco": {
        "v": 107199859817.267,
        "year": 2022
      },
      "mil": {
        "v": 2494887483.1484,
        "year": 2011
      }
    }
  }
} /* @generated-json-end */
